Naver login android sdk upgrade 5.1.0
react-native-seoul/react-native-naver-login pull request #121
Opened 2022-05-19 06:20 UTC by kentakang

Resolve #102 #112 

* Gradle 버전을 7.0.2로 업그레이드하였습니다.
* 네아로 안드로이드 SDK 버전을 5.1.0 버전으로 업데이트 후, 변경된 API를 적용하였습니다.

2022-05-19 06:20 UTC, kentakang commented
@hyochan

2022-05-19 07:12 UTC, hyochan requested changes

2022-05-19 07:12 UTC, hyochan commented on android/src/main/java/com/dooboolab/naverlogin/RNNaverLoginModule.java
>    }
null check를 해줘야하지 않을까요?

2022-05-19 07:12 UTC, hyochan commented on android/src/main/java/com/dooboolab/naverlogin/RNNaverLoginModule.java
>          public void run() {
혹시 이부분을 날려도 무방한가요? 새로운 액티비티를 명시적으로 띄워야 하는지 궁금해서 번거로우시겠지만 테스트 해주시면 도움이 될 것 같아요~!  🙏

2022-05-19 07:13 UTC, hyochan commented
> @hyochan

소중한 `PR` 날려주셔서 감사합니다 🙏.
리뷰 확인해주시면 감사하겠습니다.

2022-05-19 07:36 UTC, kentakang commented on android/src/main/java/com/dooboolab/naverlogin/RNNaverLoginModule.java
>          public void run() {
@hyochan UiThreadUtil.runOnUiThread 부분 말씀주시는건가요?

2022-05-19 07:51 UTC, kentakang commented on android/src/main/java/com/dooboolab/naverlogin/RNNaverLoginModule.java
>          public void run() {
해당 코드 제거하더라도 정상 동작합니다 :)

2022-05-19 08:00 UTC, kentakang commented
@hyochan Null 체크 코드 추가 및, 코멘트 주신 내용에 답변드렸습니다 :)

2022-05-20 06:57 UTC, hyochan approved these changes
좋은 `PR` 감사드립니다 :)

2022-05-20 06:57 UTC, merged